# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180821_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_gamification_points',
            field=models.IntegerField(default=0, verbose_name='default gamification points'),
        ),
    ]
