# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_default_gamification_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='default_gamification_points',
            field=models.IntegerField(default=100, verbose_name='default gamification points'),
        ),
    ]
