# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import taiga.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_burnup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='burndown_forecast_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=taiga.projects.models.get_project_file_path, verbose_name='burndown forecast image'),
        ),
        migrations.AddField(
            model_name='project',
            name='burnup_forecast_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=taiga.projects.models.get_project_file_path, verbose_name='burnup forecast image'),
        ),
        migrations.AddField(
            model_name='project',
            name='cfd_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=taiga.projects.models.get_project_file_path, verbose_name='cfd image'),
        ),
        migrations.AddField(
            model_name='project',
            name='us_dependencies_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=taiga.projects.models.get_project_file_path, verbose_name='US dependencies image'),
        ),
    ]
