# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import taiga.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180910_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='velocity_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=taiga.projects.models.get_project_file_path, verbose_name='velocity image'),
        ),
    ]
