# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-21 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_historyentry_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='watched',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='watched',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='notifypolicy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_policies', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='notifypolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='history_entries',
            field=models.ManyToManyField(related_name='_historychangenotification_history_entries_+', to='history.HistoryEntry', verbose_name='history entries'),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='notify_users',
            field=models.ManyToManyField(related_name='_historychangenotification_notify_users_+', to=settings.AUTH_USER_MODEL, verbose_name='notify users'),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterUniqueTogether(
            name='watched',
            unique_together=set([('content_type', 'object_id', 'user', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='notifypolicy',
            unique_together=set([('project', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='historychangenotification',
            unique_together=set([('key', 'owner', 'project', 'history_type')]),
        ),
    ]
