# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import taiga.projects.notifications.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='slug')),
                ('estimated_start', models.DateField(verbose_name='estimated start date')),
                ('estimated_finish', models.DateField(verbose_name='estimated finish date')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='finish date')),
                ('closed', models.BooleanField(default=False, verbose_name='is closed')),
                ('disponibility', models.FloatField(blank=True, default=0.0, null=True, verbose_name='disponibility')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
            ],
            options={
                'verbose_name': 'milestone',
                'verbose_name_plural': 'milestones',
                'ordering': ['project', 'created_date'],
                'permissions': (('view_milestone', 'Can view milestone'),),
            },
            bases=(taiga.projects.notifications.mixins.WatchedModelMixin, models.Model),
        ),
    ]
