# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import taiga.projects.milestones.models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_auto_20180821_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='burndown_forecast_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=taiga.projects.milestones.models.get_milestone_file_path, verbose_name='burndown forecast image'),
        ),
    ]
